{{-- Componente global: convierte selects extensos en búsquedas. Los talles admiten búsquedas desde un carácter. --}}
<style>
.erp-remote-select{position:relative}.erp-remote-select>select{display:none!important}.erp-remote-results{display:none;position:absolute;z-index:1100;top:calc(100% + 2px);left:0;right:0;max-height:260px;overflow:auto;background:var(--bs-body-bg);border:1px solid #8c57ff;border-radius:.4rem;box-shadow:0 .5rem 1.25rem rgba(47,43,61,.2);padding:.35rem}.erp-remote-select.is-open .erp-remote-results{display:block}.erp-remote-option{display:block;width:100%;border:0;background:transparent;color:var(--bs-body-color);text-align:left;padding:.55rem .7rem;border-radius:.3rem}.erp-remote-option:hover,.erp-remote-option:focus{background:#8c57ff;color:#fff}.erp-remote-message{padding:.65rem;color:var(--bs-secondary-color);font-size:.875rem}
</style>
<script>
const erpIsSizeSelect=select=>{
 const identifiers=[select?.id,select?.name,select?.dataset?.remoteUrl,select?.getAttribute?.('aria-label')]
  .filter(Boolean).join(' ').toLowerCase();
 const label=select?.id?document.querySelector(`label[for="${CSS.escape(select.id)}"]`)?.textContent?.toLowerCase()||'':'';
 return /(^|[^a-z])(size|sizes|talle|talles)([^a-z]|$)/.test(`${identifiers} ${label}`);
};
const erpSelectSearchMinimum=select=>Number(select?.dataset?.remoteMinimum|| (erpIsSizeSelect(select)?1:3));
window.erpEnhanceRemoteSelect=window.erpEnhanceRemoteSelect||function(select,settings={}){
 if(!select||select._remoteSelect)return select?select._remoteSelect:null;
 const url=settings.url||select.dataset.remoteUrl||`${window.APP_BASE_URL}/api/products`,minimum=Number(settings.minimum||erpSelectSearchMinimum(select));
 const wrapper=document.createElement('div');wrapper.className='erp-remote-select';select.parentNode.insertBefore(wrapper,select);wrapper.appendChild(select);
 const input=document.createElement('input');input.type='search';input.className=select.dataset.remoteInputClass||'form-control';input.placeholder=select.dataset.remotePlaceholder||`Ingresá ${minimum} caracteres...`;input.autocomplete='off';if(select.required){input.required=true;select.required=false}
 const results=document.createElement('div');results.className='erp-remote-results';wrapper.append(input,results);let timer,controller;
 const close=()=>wrapper.classList.remove('is-open');
 const label=item=>[item.code,item.name,item.document_number??item.identification_number,item.bar_code].filter(Boolean).join(' · ');
 const choose=item=>{select.innerHTML='';const option=new Option(label(item),item.id,true,true);option.dataset.price=item.price_a_with_tax??item.price_a??0;select.add(option);select._remoteSelected=item;select.dispatchEvent(new Event('change',{bubbles:true}));input.value=label(item);close()};
 const search=async()=>{const term=input.value.trim();if(term.length<minimum){results.innerHTML=`<div class="erp-remote-message">Ingresá al menos ${minimum} caracteres.</div>`;wrapper.classList.add('is-open');return}controller?.abort();controller=new AbortController();results.innerHTML='<div class="erp-remote-message">Buscando...</div>';wrapper.classList.add('is-open');try{const target=new URL(url,location.origin);target.searchParams.set('search',term);target.searchParams.set('lookup','1');target.searchParams.set('per_page','20');const response=await fetch(target,{headers:{Accept:'application/json'},signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.message||'Error');const items=data.data??data;results.innerHTML=items.length?'':'<div class="erp-remote-message">No se encontraron resultados.</div>';items.forEach(item=>{const button=document.createElement('button');button.type='button';button.className='erp-remote-option';button.textContent=label(item);button.onclick=()=>choose(item);results.appendChild(button)})}catch(error){if(error.name!=='AbortError')results.innerHTML='<div class="erp-remote-message text-danger">No se pudo realizar la búsqueda.</div>'}};
 input.oninput=()=>{clearTimeout(timer);if(!input.value.trim()){select.innerHTML='<option value=""></option>';select.value='';select._remoteSelected=null;select.dispatchEvent(new Event('change',{bubbles:true}))}timer=setTimeout(search,300)};input.onfocus=()=>{results.innerHTML=`<div class="erp-remote-message">Ingresá al menos ${minimum} caracteres.</div>`;wrapper.classList.add('is-open')};document.addEventListener('click',event=>{if(!wrapper.contains(event.target))close()});
 select.addEventListener('change',()=>{if(!select.value)input.value='';else if(select.selectedOptions[0]&&!input.value)input.value=select.selectedOptions[0].text});select._remoteSelect={input,search,choose,clear(){input.value='';select.innerHTML='<option value=""></option>';select.value='';select._remoteSelected=null;close()}};return select._remoteSelect;
};
window.erpEnhanceLargeSelect=window.erpEnhanceLargeSelect||function(select,minimum=3){
 if(!select||select._largeSelect||select._remoteSelect||select.multiple||select.closest('[data-erp-multiselect]'))return null;
 const wrapper=document.createElement('div');wrapper.className='erp-remote-select';select.parentNode.insertBefore(wrapper,select);wrapper.appendChild(select);const input=document.createElement('input');input.type='search';input.className='form-control';input.placeholder=`Ingresá ${minimum} caracteres...`;input.autocomplete='off';if(select.required){input.required=true;select.required=false}const results=document.createElement('div');results.className='erp-remote-results';wrapper.append(input,results);
 const close=()=>wrapper.classList.remove('is-open');const render=()=>{const term=input.value.trim().toLowerCase();if(term.length<minimum){results.innerHTML=`<div class="erp-remote-message">Ingresá al menos ${minimum} caracteres.</div>`;return}const matches=[...select.options].filter(option=>option.value&&option.text.toLowerCase().includes(term)).slice(0,30);results.innerHTML=matches.length?'':'<div class="erp-remote-message">No se encontraron resultados.</div>';matches.forEach(option=>{const button=document.createElement('button');button.type='button';button.className='erp-remote-option';button.textContent=option.text;button.onclick=()=>{select.value=option.value;select.dispatchEvent(new Event('change',{bubbles:true}));input.value=option.text;close()};results.appendChild(button)})};input.onfocus=()=>{wrapper.classList.add('is-open');render()};input.oninput=()=>{wrapper.classList.add('is-open');if(!input.value){select.value='';select.dispatchEvent(new Event('change',{bubbles:true}))}render()};select.addEventListener('change',()=>{if(!select.value)input.value=''});document.addEventListener('click',event=>{if(!wrapper.contains(event.target))close()});select._largeSelect={input,render};return select._largeSelect;
};
function erpScanLargeSelects(root=document){root.querySelectorAll?.('select[data-remote-url]').forEach(select=>erpEnhanceRemoteSelect(select));root.querySelectorAll?.('select:not([data-remote-url])').forEach(select=>{if(select.options.length>=20)erpEnhanceLargeSelect(select,erpSelectSearchMinimum(select))})}
document.addEventListener('DOMContentLoaded',()=>erpScanLargeSelects());let erpSelectScanTimer;new MutationObserver(()=>{clearTimeout(erpSelectScanTimer);erpSelectScanTimer=setTimeout(()=>erpScanLargeSelects(),100)}).observe(document.documentElement,{childList:true,subtree:true});
</script>
