<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('roles',function(Blueprint$t){$t->id();$t->string('name')->unique();$t->boolean('is_active')->default(true);$t->boolean('is_system')->default(false);$t->timestamps();});
  Schema::create('permissions',function(Blueprint$t){$t->id();$t->string('key')->unique();$t->string('name');$t->string('module')->nullable();$t->timestamps();});
  Schema::create('permission_role',function(Blueprint$t){$t->foreignId('role_id')->constrained()->cascadeOnDelete();$t->foreignId('permission_id')->constrained()->cascadeOnDelete();$t->primary(['role_id','permission_id']);});
  Schema::table('users',function(Blueprint$t){$t->foreignId('role_id')->nullable()->after('id')->constrained()->nullOnDelete();$t->string('username')->nullable()->unique()->after('role_id');$t->string('first_name')->nullable()->after('name');$t->string('last_name')->nullable()->after('first_name');$t->date('birth_date')->nullable();$t->date('hire_date')->nullable();$t->string('phone')->nullable();$t->string('country')->nullable();$t->string('province')->nullable();$t->string('address')->nullable();$t->string('neighborhood')->nullable();$t->decimal('max_discount_percentage',8,4)->nullable();$t->decimal('sales_commission_percentage',8,4)->nullable();$t->decimal('collections_commission_percentage',8,4)->nullable();$t->decimal('profit_commission_percentage',8,4)->nullable();$t->boolean('is_active')->default(true);$t->timestamp('last_login_at')->nullable();});
  $now=now();$admin=DB::table('roles')->insertGetId(['name'=>'Administrador','is_active'=>1,'is_system'=>1,'created_at'=>$now,'updated_at'=>$now]);foreach(['Vendedor','Cajero'] as $role)DB::table('roles')->insert(['name'=>$role,'is_active'=>1,'is_system'=>1,'created_at'=>$now,'updated_at'=>$now]);
  $actions=['consultar','crear','editar','eliminar','anular','exportar','administrar'];foreach($actions as $action){$id=DB::table('permissions')->insertGetId(['key'=>'system.'.$action,'name'=>ucfirst($action),'module'=>'system','created_at'=>$now,'updated_at'=>$now]);DB::table('permission_role')->insert(['role_id'=>$admin,'permission_id'=>$id]);}DB::table('users')->whereNull('role_id')->update(['role_id'=>$admin,'is_active'=>1]);
 }
 public function down():void{Schema::table('users',function(Blueprint$t){$t->dropConstrainedForeignId('role_id');$t->dropColumn(['username','first_name','last_name','birth_date','hire_date','phone','country','province','address','neighborhood','max_discount_percentage','sales_commission_percentage','collections_commission_percentage','profit_commission_percentage','is_active','last_login_at']);});Schema::dropIfExists('permission_role');Schema::dropIfExists('permissions');Schema::dropIfExists('roles');}
};
